---
- name: Download Code Server Installer
  get_url:
    url: https://code-server.dev/install.sh
    dest: /opt/code-server-install.sh

- name: Install Code Server
  command: sh /opt/code-server-install.sh
  register: code_server_install
  ignore_errors: true

- name: Ensure code-server dir exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "student{{ hostvars[inventory_hostname].ansible_student_number }}"
    group: "student{{ hostvars[inventory_hostname].ansible_student_number }}"
  with_items:
    - "/home/student{{ hostvars[inventory_hostname].ansible_student_number }}/.config/code-server/"
    - "/home/student{{ hostvars[inventory_hostname].ansible_student_number }}/.local/share/code-server/User/"

- name: Template over code-server.yaml
  template:
    src: code-server-config.yaml.j2
    dest: "/home/student{{ hostvars[inventory_hostname].ansible_student_number }}/.config/code-server/config.yaml"
    owner: "student{{ hostvars[inventory_hostname].ansible_student_number }}"
    group: "student{{ hostvars[inventory_hostname].ansible_student_number }}"

- name: Template over code-server settings.json
  template:
    src: code-server-user-settings.json.j2
    dest: "/home/student{{ hostvars[inventory_hostname].ansible_student_number }}/.local/share/code-server/User/settings.json"
    owner: "student{{ hostvars[inventory_hostname].ansible_student_number }}"
    group: "student{{ hostvars[inventory_hostname].ansible_student_number }}"
    
- name: Start code-server
  service:
    name: "code-server@student{{ hostvars[inventory_hostname].ansible_student_number }}"
    state: restarted
    enabled: yes