---
- name: Create generation directory
  file:
    path: "{{ generation_directory }}"
    state: directory

- name: Install passlib locally
  pip:
    name: passlib
    state: present
  when: tower_job_id is not defined

- name: Generate Proctor Password Hash
  command: 'python3 -c ''import passlib.hash; print(passlib.hash.sha512_crypt.hash("{{ proctor_password }}"))'''
  register: generated_proctor_password_hash

- name: Generate Student Password Hash
  command: 'python3 -c ''import passlib.hash; print(passlib.hash.sha512_crypt.hash("{{ student_password }}"))'''
  register: generated_student_password_hash

- name: Retrieve IBM Cloud cURL API Bearer Token
  uri:
    url: "https://iam.cloud.ibm.com/identity/token"
    method: POST
    body_format: form-urlencoded
    body:
      grant_type: urn:ibm:params:oauth:grant-type:apikey
      apikey: "{{ ibmcloud_api_key }}"
    headers:
      Accept: application/json
  register: curl_api_token

- name: Set IBM Cloud API Token facts
  set_fact:
    ibm_api_token: "{{ curl_api_token.json.token_type }} {{ curl_api_token.json.access_token }}"

- name: Retrieve image list
  ibm.cloudcollection.ibm_is_images_info:
    ibmcloud_api_key: "{{ ibmcloud_api_key }}"
    region: "{{ region }}"
  register: images_list
  tags:
    - image_list

- name: Set VM image name/id dictionary fact
  set_fact:
    cacheable: True
    image_dict: "{{ images_list.resource.images |
      items2dict(key_name='name', value_name='id') }}"
  tags:
    - image_list

- name: Log into RH SSO API
  uri:
    url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    body_format: form-urlencoded
    method: POST
    body:
      grant_type: refresh_token
      client_id: rhsm-api
      refresh_token: "{{ rhsm_api_token }}"
  register: rh_sso_reg
  tags:
    - tower_license

- name: Trigger Manifest Export
  uri:
    url: "https://api.access.redhat.com/management/v1/allocations/{{ rhsm_tower_allocation_uuid }}/export"
    status_code: 200
    headers:
      Authorization: "Bearer {{ rh_sso_reg.json.access_token }}"
  register: trigger_manifest_export_reg
  tags:
    - tower_license

- name: Check status of Manifest ExportJob
  uri:
    url: "{{ trigger_manifest_export_reg.json.body.href }}"
    status_code: 200
    headers:
      Authorization: "Bearer {{ rh_sso_reg.json.access_token }}"
  register: check_manifest_export_reg
  until: check_manifest_export_reg.status == 200
  retries: 10
  delay: 10
  ignore_errors: true
  tags:
    - tower_license

- name: Download Manifest
  get_url:
    url: "{{ check_manifest_export_reg.json.body.href }}"
    dest: "{{ generation_directory }}/tower_sub_manifest.zip"
    headers:
      Authorization: "Bearer {{ rh_sso_reg.json.access_token }}"
  tags:
    - tower_license