---
domain: ibm.example.com
ibmcloud_api_key: someReallyReallyReallyLongString

guid: an51
workshop_id: ansible-automation
workshop_shortcode: ansible

proctor_password: changeme987
student_password: changeme123

student_count: 2
student_node_count: 1

## Tower now needs a RH subscription
tower_rh_subscription_username: you@example.com
tower_rh_subscription_password: securePassw0rd
tower_rh_subscription_pool_id: l0ngstr1ng
tower_rh_subscription_server_hostname: "{{ rhsm_server }}"

generation_directory: "/tmp/.blue-forge/{{ workshop_id }}/{{ guid }}"

region: us-east
regional_zone: us-east-3

# dnsnb_provider: aws, digitalocean
dnsnb_provider: aws

dnsnb_persistent_zone: "{{ domain }}"
dnsnb_delegated_zone: "{{ guid }}"

# AWS Route53
dnsnb_aws_access_key: AKIAYOLOLOLUAFYKGSF7
dnsnb_aws_secret_key: someReallyReallyReallyLongString
# DigitalOcean Domains
dnsnb_do_pat: someReallyReallyReallyLongString